from config_0 import *

TRAIT_EXTRA_REL_TOPK_STATE = 10
TRAIT_EXTRA_REL_TOPK_EPISODE = 5
STATE_STATE_EXTRA_REL_TOPK = 8
STATE_EPISODE_EXTRA_REL_TOPK = 4

MAX_KEYWORDS = 8
MAX_DOMAIN_LABELS = 8
MIN_DOMAIN_LABELS = 6
